Repository StanfordAHA/garnet, pull requests merged in 2019-06, with the labels that each got.

#294 Add CoSA problems for Garnet PE Tile Interconnect
  .travis.yml
  tests/test_pe_tile_formal/problem.txt
  tests/test_pe_tile_formal/source.vlist
  tests/test_pe_tile_formal/test_pe_tile_interconnect.py
Labels: testing

#320 simplifies buffer valid logic - same for all modes (the way it should have been in the first place)
  memory_core/README.md
  memory_core/genesis_new/doublebuffer_control.svp
  memory_core/genesis_new/memory_core.svp
  memory_core/memory_core.py
  memory_core/memory_core_magma.py
  tests/test_interconnect/test_interconnect_cgra.py
Labels: memory

#324 fix wen RTL BUG
  memory_core/genesis_new/doublebuffer_control.svp
Labels: bug
